### ISSUE TITLE
Cata Classic: Error in Loadscreen

### ISSUE THREAD

**Issue by sobrino89** [silverwind/idTip#110]
Right now I am searching for addons causing errors because I have problems with my raid logs.
I don't suspect this has anything to do with it, but as I encountered the error I wanted to report it.

Everytime I log in with a character I get this error during the loadscreen:

```
3x ...rfaceidTip_CommunityFork/clients/classic.lua:84: hooksecurefunc(): SpellButton_OnEnter is not a function
[string "=[C]"]: in function 'hooksecurefunc'
[string "@idTip_CommunityFork/clients/classic.lua"]:84: in main chunk

Locals:
```

**Comment by silverwind** [comment]
This shouldn't happen with latest version because it checks for nonexistant functions and you appear to be using a forked version, so try installing latest
