### ISSUE TITLE
bonus id is not working

### ISSUE THREAD

**Issue by soso-15** [silverwind/idTip#111]
my wow version is retail.

**Comment by silverwind** [comment]
I don't think this is possible anymore to show in v10 or higher. Blizzard removed the https://warcraft.wiki.gg/wiki/UIHANDLER_OnTooltipSetItem function and provides TooltipDataProcessor as alternative but those links that the TooltipDataProcessor gives do not contain any BonusIDs or GemIDs it appears.

https://github.com/silverwind/idTip/commit/ef0d830d7a58b06cdde0c9702e3446dbc0bed314 makes it so the item processing again uses itemLink for item tooltips in v10, so if Blizzard decides to fix this, it will start working again.

**Comment by soso-15** [comment]
but another fork of this addon can show bonus id in game right now.
[(https://github.com/ItsJustMeChris/idTip-Community-Fork)]
though it throws some errors out sometimes because it is abandoned.
