### ISSUE TITLE
Feature Request: Add command to toggle IDs on/off

### ISSUE THREAD

**Issue by Taizunz** [silverwind/idTip#112]
The old community fork of this appears to have that functionality ( https://github.com/ItsJustMeChris/idTip-Community-Fork ). 
I'd love if the main addon got it too, seeing as you're actively maintaining it.

**Comment by silverwind** [comment]
Hmm I don't see much of a point, you could use https://www.curseforge.com/wow/addons/acp to toggle on/off the addon itself.

**Comment by Taizunz** [comment]
Loading/unloading an addon still requires a /reload. I'm not interested in that.
And I already have an in-game addon control panel via ElvUI.

**Comment by silverwind** [comment]
https://github.com/silverwind/idTip/commit/5e6be842c3e6ddf84deae39197acda079a1ca32d adds an option panel with a checkbox for to disable the ids, but it's still better to completely disable the addon so that event handlers won't register etc as there is not unregister code.

**Comment by Taizunz** [comment]
Thank you so much for this.
After you added this I quickly whipped up a simple macro `/run idTipCheckEnabled:Click()` to toggle it on/off via a button in my bars, which is good enough for me in terms of having a chat command for it.

**Comment by silverwind** [comment]
Yes, options load on-demand. Some slash commands might be in order.
