### ISSUE TITLE
spellid no longer show

### ISSUE THREAD

**Issue by blecaplol** [silverwind/idTip#114]
i update to the latest version and it no longer display the spell id or the addon not working at all but when i downgrade 11.2.0 it works.

**Comment by silverwind** [comment]
Which WoW version is this on? Any errors visible?

**Comment by blecaplol** [comment]
on retail. not sure. just skimping through bugsack i dont see any "spellidtip" error

**Comment by silverwind** [comment]
Still an issue? Also check the options panel for the addon that the relevant ids are actually enabled.

**Comment by blecaplol** [comment]
it seems ok now thanks!
