### ISSUE TITLE
TraitNode/TraitNodeEntry/TraitDefinitionIDs on Talents

### ISSUE THREAD

**Issue by ljosberinn** [silverwind/idTip#118]
would be handy to have these on the talents

the community fork version had this in place, unsure if it still applies:
```lua
    hooksecurefunc(TalentDisplayMixin, "SetTooltipInternal", function(self)
      if self then
        local spellID = self:GetSpellID()
        if spellID then
          local overrideSpellID = C_SpellBook.GetOverrideSpell(spellID)

          IDTip:addLine(GameTooltip, overrideSpellID, IDTip.kinds.spell)
          IDTip:addLine(GameTooltip, self.entryID, IDTip.kinds.traitentry)
          IDTip:addLine(GameTooltip, self.definitionID, IDTip.kinds.traitdef)
          IDTip:addLine(GameTooltip, C_ClassTalents.GetActiveConfigID(), IDTip.kinds.traitconfig)
          IDTip:addLine(GameTooltip, self:GetNodeInfo().ID, IDTip.kinds.ctrait)
        end
      end
    end)
```

**Comment by silverwind** [comment]
What purpose do those 4 IDs serve? I'm hesitant to add IDs that have no real purpose.

**Comment by silverwind** [comment]
Hmm yes, I may consider adding them in default-disabled state. There's 4 IDs in above code, are all 4 needed or can it be reduced?

**Comment by ljosberinn** [comment]
Depends, if you plan on putting this behind a disabled-by-default state then I'd prefer having all. If not, the ActiveConfigID is the least relevant, but the others afraid are all important.

**Comment by silverwind** [comment]
Added all except configId because that one is not specific to the hovered node. They are disabled by default and need to be enabled in the options panel.

<img width="236" alt="image" src="https://github.com/user-attachments/assets/1e2d4098-9143-46e0-92c4-8d409f0dd982">

**Comment by ljosberinn** [comment]
cheers! much appreciated
