### ISSUE TITLE
QuestID should show in more places

### ISSUE THREAD

**Issue by yoshimo** [silverwind/idTip#120]
I think the quest id should show on the left side in the detail view and as a mouse over tooltip on the quest tracker on the far right side
![WoWScrnShot_080124_213024](https://github.com/user-attachments/assets/67ef5576-4e54-479b-b912-2be20aab1b90)

I also think it should show in the gossip frame when you accept a quest:

![image](https://github.com/user-attachments/assets/fa0e75d9-1f4e-4002-98c8-b4563f89dec8)

**Comment by silverwind** [comment]
The thing is this addons modifies tooltips only, and if there is no tooltip it's questionable where it would be added.
