### ISSUE TITLE
Crafting Frame: ItemID 0

### ISSUE THREAD

**Issue by ssateneth** [silverwind/idTip#13]
all item IDs now show as 0 instead of true item ID. blizz added an extra field to item links, so the addon is broken now.

**Comment by silverwind** [comment]
I can't reproduce this on 6.2.

While [there was a change](http://wow.gamepedia.com/Patch_6.2.0/API_changes) to ItemIDs, it should be compatible (It would only have broken this addon if the new value was inserted before the itemID).

@ssateneth where exactly are you seeing this 0 value? And you are on 6.2 live, I assume?

**Comment by ssateneth** [comment]
Sorry for leaving this ticket. I just enabled the addon again and now all the values are correct (no more 0's). It might have been an older addon interfering with idtip. Carry on :)

**Comment by ssateneth** [comment]
Actually, I found out where I saw the 0 ID again. Profession windows. If you mouse over a crafted item, its ID shows as 0.

http://gyazo.com/2c4ab96554c6811db2ba57ab46bb202a

**Comment by WetU** [comment]
To fix this problem, edit core.lua file.

Open up core.lua file. and find the local function attachItemTooltip(self) at 95 line
make it look like this

local function attachItemTooltip(self)
    local link = select(2, self:GetItem())
    if link then
        local id = select(3, strfind(link, "^|%x+|Hitem:(%-?%d+):(%d+):(%d+):(%d+):(%d+):(%d+):(%-?%d+):(%-?%d+)"));
        if id == "0"  and TradeSkillFrame:IsVisible() then
          TradeSkillWindowMouseFocus = (GetMouseFocus():GetName())
          if TradeSkillWindowMouseFocus == "TradeSkillSkillIcon" then
            id = GetTradeSkillItemLink(TradeSkillFrame.selectedSkill):match("item:(%d+):") or nil
          elseif TradeSkillWindowMouseFocus ~= "TradeSkillSkillIcon" then
            for i=1, 8 do
              if TradeSkillWindowMouseFocus == "TradeSkillReagent"..i then
                id = GetTradeSkillReagentItemLink(TradeSkillFrame.selectedSkill, i):match("item:(%d+):") or nil
                break
              end
            end
          end
        end
        addLine(self, id, types.item)
    end
end

**Comment by ssateneth** [comment]
Works, thanks! :)

**Comment by silverwind** [comment]
@WetU would love if you could do a properly formatted pull request with this change!
