### ISSUE TITLE
Map ID feature

### ISSUE THREAD

**Issue by Voxxel** [silverwind/idTip#20]
Hi silverwind,

I'd like to ask if it is possible to display the map IDs by this addon?

I went through a serious search for some maps on Wowhead that are in the game already with no success. Especially underground and sub-zone maps are hard to find. 

Would be a useful addition to the addon.

**Comment by silverwind** [comment]
There are no tooltips in the map windows where I could add those to and I don't really want to touch anything besides tooltips, so I think this addition would be better done on a map addon.
