### ISSUE TITLE
Toy IDs

### ISSUE THREAD

**Issue by Suggesti0ns** [silverwind/idTip#22]
Hello.
Any chance you could add the itemIDs to toys?
cheers!

**Comment by silverwind** [comment]
You mean in the toy box? Not sure if they are refered there by their ItemID or more likely their SpellID, e.g.

http://www.wowhead.com/item=87214

vs

http://www.wowhead.com/spell=127129

Oh, and I don't have a test account with toys.

**Comment by Suggesti0ns** [comment]
Yeah - in the toybox.

I've been having a play around - I don't know much about LUA but I'm trying to learn :p

I tried this:

`hooksecurefunc(GameTooltip, "SetToyByItemID", function(self, id)`
`print(self,id)`
`end)`

And had success in the toybox! - it was returning item id's, so this works for the toybox:

`hooksecurefunc(GameTooltip, "SetToyByItemID", function(self, id)`
`if id then addLine(self, id, types.item) end`
`end)`

Now I can't figure out why they don't show on toys on the action bar.
Mousing over one doesn't fire the function
`attachItemTooltip`

Would there be a line similar to
`GameTooltip:HookScript("OnTooltipSetItem", attachItemTooltip)`
That needs to be added?


And unimportantly, I think the spell that goes with
http://www.wowhead.com/item=87214
is actually
http://www.wowhead.com/spell=126459

**Comment by silverwind** [comment]
There's `GameTooltip:SetToyByItemID(self.itemID)`:

https://github.com/Gethe/wow-ui-source/blob/live/AddOns/Blizzard_Collections/Blizzard_ToyBox.lua#L124

**Comment by silverwind** [comment]
There might be a `toy` attribute on action buttons:

https://github.com/Gethe/wow-ui-source/blob/live/FrameXML/SecureTemplates.lua#L389

Didn't find anything else about it. Maybe it uses `OnTooltipSetItem`.

**Comment by silverwind** [comment]
ItemIDs of toys are supported as of https://github.com/silverwind/idTip/commit/351bb06fe79ca4c7698be13d5734867e6f83c71a (8.0.0 only).
