### ISSUE TITLE
Artifact Power ID/SpellID

### ISSUE THREAD

**Issue by Tonydk** [silverwind/idTip#23]
Would it be possible to add Artifact Power and Spell IDs to the ArtifactFrame?

I've managed to show Power IDs by hooking into SetArtifactPowerByID, but I've no idea how to attach Spell IDs

local types = {
    spell       = "SpellID:",
    item        = "ItemID:",
    unit        = "NPC ID:",
    quest       = "QuestID:",
    talent      = "TalentID:",
    achievement = "AchievementID:",
    ability     = "AbilityID:",
    currency    = "CurrencyID:",
    artifactpower = "ArtifactPowerID:"
}

hooksecurefunc(GameTooltip, "SetArtifactPowerByID", function(self, id)
	if id then 
		addLine(self, id, types.artifactpower) 
	end
end)

**Comment by Tonydk** [comment]
Update, someone helped me out: this will add power and spell IDs to the tooltip:

-- ArtifactPowerIDs
hooksecurefunc(GameTooltip, "SetArtifactPowerByID", function(self, id)
    if id then 
    	local spellid = C_ArtifactUI.GetPowerInfo(id)
        addLine(self, id, types.artifactpower);
        addLine(self, spellid, types.spell)
    end
end)

**Comment by silverwind** [comment]
Nice. Looking forward to your pull request 👍

**Comment by Tonydk** [comment]
Sent!
