### ISSUE TITLE
Add bonusID, enchantID, GemID on item

### ISSUE THREAD

**Issue by Kutikuti** [silverwind/idTip#30]
Hi,
Really like your addon, i made an addition to it. I added bonusID, enchantID and gemID to items. It makes comparing item with simulationcraft really easier.
Maybe you could add it, or with a key modifier.
I made a fork if you want to take a look : https://github.com/Kutikuti/idTip

**Comment by silverwind** [comment]
Thanks, I'll definitely will check that out and see what I can integrate (thought my ability to test is limited as I only have a starter account available).

**Comment by silverwind** [comment]
Fixed in https://github.com/silverwind/idTip/commit/c717c1dad2fff58bce24a90226f7279ee4ea9b04.
