### ISSUE TITLE
8.0 errors

### ISSUE THREAD

**Issue by Voxxel** [silverwind/idTip#34]
Hey Silverwind,
I don't know if you're in Beta for now but idTip has some displaying issues in 8.0. My main headache is that the latest workaround for displaying quest IDs on the tooltip popup in the map/quest log frame is not working anymore. I did some legwork at wowinterface about this issue, too bad I don't understand a single word of it:

http://www.wowinterface.com/forums/showpost.php?p=327639&postcount=10

Item and NPC IDs are all good.

- spell IDs on tooltips in spell book, action bar, mount panel are missing, but spells by the boss ability links in the journal are displayed correctly. If I paste the spells into the chat and hover the mouse it's also correctly displayed.

**Comment by Rantsi92** [comment]
I am also dumped by this. This addon would help it alot while checking trough new BFA Spells and Ablities. If i would know how to fix this code myself i would do so.

**Comment by silverwind** [comment]
Fixed on git master, please install manually from GitHub until BfA release.
