### ISSUE TITLE
broken on new patch 8.0.1

### ISSUE THREAD

**Issue by ssateneth** [silverwind/idTip#35]
doesnt work on BFA 8.0.1. here is error log when covering over a buff tooltip https://pastebin.com/raw/xGsKETGW

**Comment by silverwind** [comment]
This should already be fixed (but not released), please try again with [current master](https://github.com/silverwind/idTip/archive/master.zip).

**Comment by Takkero** [comment]
@silverwind it works but u have to upload it to CURSE so the right release will be downloader from all users  ! 👍

**Comment by silverwind** [comment]
I can't publish it because it's incompatible with 7.x.x. It will be updated on Curse once BfA is live.

**Comment by ascott18** [comment]
The patch is live now - you should be able to push it out to Curse.

**Comment by Adagior** [comment]
it works well in 8.01

**Comment by silverwind** [comment]
Published idTip-8.0.0 to Curse.
