### ISSUE TITLE
Spell Ids on spelllink doesn't show since BfA

### ISSUE THREAD

**Issue by arbi316** [silverwind/idTip#42]
It doesn't show Spell Ids on spelllinks in chat frame

**Comment by arbi316** [comment]
Found a bug.
`local function onSetHyperlink(self, link)
  local kind, id = string.match(link,"^(%a+):(%d+)")
  addLineByKind(self, kind, id)
end
`

edit like below

`local function onSetHyperlink(self, link)
  local kind, id = string.match(link,"^(%a+):(%d+)")
  addLineByKind(self, id, kind)
end
`

**Comment by silverwind** [comment]
Good find, thanks!
