### ISSUE TITLE
Error in 8.1.5

### ISSUE THREAD

**Issue by CMcFadyen** [silverwind/idTip#44]
Looks like it's caused by the removal of WorldMapTooltip

59x idTip\idTip-8.1.2.lua:42: attempt to index local 'tooltip' (a nil value)
idTip\idTip-8.1.2.lua:42: in function <idTip\idTip.lua:35>
idTip\idTip-8.1.2.lua:350: in function <idTip\idTip.lua:349>
[C]: in function `TaskPOI_OnEnter'
...rd_SharedMapDataProviders\WorldQuestDataProvider.lua:389: in function <...rd_SharedMapDataProviders\WorldQuestDataProvider.lua:388>

Locals:
tooltip = nil
id = 51502
kind = "QuestID"
frame = nil
text = nil
(for index) = 1
(for limit) = 15
(for step) = 1

**Comment by ChadCloman** [comment]
Another instance (no locals):

```
Message: Interface\AddOns\idTip\idTip.lua:42: attempt to index local 'tooltip' (a nil value)
Time: Tue Mar 12 18:32:30 2019
Count: 1
Stack: Interface\AddOns\idTip\idTip.lua:42: attempt to index local 'tooltip' (a nil value)
[C]: ?
Interface\AddOns\idTip\idTip.lua:42: in function <Interface\AddOns\idTip\idTip.lua:35>
Interface\AddOns\idTip\idTip.lua:350: in function <Interface\AddOns\idTip\idTip.lua:349>
[C]: in function `TaskPOI_OnEnter'
...rd_SharedMapDataProviders\WorldQuestDataProvider.lua:389: in function <...rd_SharedMapDataProviders\WorldQuestDataProvider.lua:388>

```

**Comment by ssateneth** [comment]
same. i get error on hovering on WQs icons in world map

`Message: Interface\AddOns\idTip\idTip.lua:42: attempt to index local 'tooltip' (a nil value)
Time: Tue Mar 12 22:13:44 2019
Count: 1
Stack: Interface\AddOns\idTip\idTip.lua:42: attempt to index local 'tooltip' (a nil value)
[C]: ?
Interface\AddOns\idTip\idTip.lua:42: in function <Interface\AddOns\idTip\idTip.lua:35>
Interface\AddOns\idTip\idTip.lua:350: in function <Interface\AddOns\idTip\idTip.lua:349>
[C]: in function `TaskPOI_OnEnter'
...rd_SharedMapDataProviders\WorldQuestDataProvider.lua:389: in function <...rd_SharedMapDataProviders\WorldQuestDataProvider.lua:388>
[C]: ?

Locals: `

**Comment by ChadCloman** [comment]
Thank you so much for fixing this. TSM requires me to use the item number for certain tasks, and I really hate having to go to wowhead to look it up. Great plug-in!
