### ISSUE TITLE
Quest IDs

### ISSUE THREAD

**Issue by silverwind** [silverwind/idTip#5]
I plan on adding these, probably on the tooltip on the map window.

**Comment by Voxxel** [comment]
Hey silverwind! Is there a way in 7.0 to display the quest IDs? I mean without manually linking them to chat and read tooltip. If still no way in quest panel, maybe elsewhere? For example, when accepting a quest print the ID in the chat?

**Comment by silverwind** [comment]
Fixed in https://github.com/silverwind/idTip/commit/2e0790d05621e1a0fb62821fcb9ef32270e3dc23!

**Comment by Voxxel** [comment]
Yay! Thanks a lot m8!
