### ISSUE TITLE
(bug) SL 9.0.1 

### ISSUE THREAD

**Issue by gaveer** [silverwind/idTip#56]
```8x idTip\idTip-8.2.1.lua:355: attempt to call global 'GetQuestLogTitle' (a nil value)
[string "@idTip\idTip-8.2.1.lua"]:355: in function <idTip\idTip.lua:354>
[string "=[C]:"]: ?
[string "=[C]:"]: ?```

**Comment by niketa-wow** [comment]
That doesn't really say anything to help see what the issue is, but I just fixed an issue with the quest log on that line.
Replace line 355 with:

```local id = C_QuestLog.GetInfo(self.questLogIndex).questID```

**Comment by nuoHep** [comment]
At least as of beta build 9.0.2.36086 you can also replace the whole hook with
```lua
hooksecurefunc("QuestMapLogTitleButton_OnEnter", function(self)
  addLine(GameTooltip, self.questID, kinds.quest)
end)
```
