### ISSUE TITLE
Current CurseForge version is not detected by addon managers

### ISSUE THREAD

**Issue by slabstone** [silverwind/idTip#58]
The current addon version available on CurseForge is 8.2.1, but addon managers only detect version 8.1.4 (tested in Twitch App, Ajour and WowUp). Since the behaviour is the same for three different addon managers I think the issue is addon related.

**Comment by slabstone** [comment]
Probably realted to 87870c53d57c30a12577333c403823e2a28d2d6c.

**Comment by silverwind** [comment]
Should be fixed, there's now only one place to store the version.
