### ISSUE TITLE
9.0.1 support

### ISSUE THREAD

**Issue by mathiasCV** [silverwind/idTip#62]
Any plan for updating the addon to the current version of the game?

**Comment by silverwind** [comment]
9.0 support was released yesterday.

**Comment by Scaver** [comment]
FYI: Twitch App shows 8.1.4 as the last version and don't provide any updates.

**Comment by silverwind** [comment]
Why's that? Curseforge shows it just fine:

https://www.curseforge.com/wow/addons/idtip/files

**Comment by mathiasCV** [comment]
![image](https://user-images.githubusercontent.com/48734340/98451961-bccf2580-2129-11eb-9025-ce42a388a8b5.png)

**Comment by silverwind** [comment]
See https://github.com/silverwind/idTip/issues/64
