### ISSUE TITLE
GetCurrencyListLink error

### ISSUE THREAD

**Issue by Stanzilla** [silverwind/idTip#63]
7x idTip\idTip-8.2.1.lua:341: attempt to call global 'GetCurrencyListLink' (a nil value)
[string "@idTip\idTip-8.2.1.lua"]:341: in function <idTip\idTip.lua:340>
[string "=[C]"]: ?
[string "=[C]"]: in function `SetCurrencyToken'
[string "*:OnEnter"]:2: in function <[string "*:OnEnter"]:1>

**Comment by silverwind** [comment]
Are you on version 9.0.0? IIRC, that error was fixed.

**Comment by Stanzilla** [comment]
Hrm, the Overwolf app only offers 8.1.4, let me download manually

**Comment by silverwind** [comment]
Yeah, this is definitely fixed.
