### ISSUE TITLE
CurseForge/Twitch Apps Won't Install 9.0.0

### ISSUE THREAD

**Issue by kstange** [silverwind/idTip#64]
I noticed there was no update showing for idTip for 9.0.1 even though it's available on the CurseForge site and listed under WoW.  The last version that shows as available is 8.1.4:

![image](https://user-images.githubusercontent.com/8593622/98323213-e9aafd80-1fae-11eb-8ebc-8edf18f28b4f.png)

If I manually install the zip file, I also get a warning in the CurseForge app:

![image](https://user-images.githubusercontent.com/8593622/98323279-13fcbb00-1faf-11eb-9a5b-cc1b0dd0db0c.png)

So it seems like somehow the release doesn't count as for WoW Retail.  Maybe it's a bug of CurseForge that you have to provide separate zip files for each WoW edition?

**Comment by silverwind** [comment]
Might have to republish. I flagged it as 9.0 compatible first, then edited and added classic. Website show it fine but I guess that may have bugged out something invisible.

**Comment by silverwind** [comment]
I've published 9.0.1, let me know if that one works.

**Comment by kstange** [comment]
It's not showing up still.  Everything looks the same in the app.

**Comment by silverwind** [comment]
Maybe try https://help.twitch.tv/s/contactsupport, number of downloads shows it's at least working for some people.

**Comment by Emmaleah** [comment]
FYI,  not working for me. but i was able to get from wowinterface. (same problem with twitch showing 8.1.5 version from 6/13/19)

**Comment by kstange** [comment]
So I tested by installing WoW Classic and there it shows versions 8.2.0 and up, all of which don't show for Retail.  I'm betting the download stats you are seeing are people running Classic.  I think there is an issue where you can't have the same release file tagged for both Classic and Retail.  Can you try making 9.0.1 just for Retail WoW?

![image](https://user-images.githubusercontent.com/8593622/98454532-11bf6b80-212b-11eb-85f5-c8661302384b.png)

**Comment by silverwind** [comment]
I've uploaded separate versions for classic and retail with proper TOC numbers in them too.

**Comment by kstange** [comment]
Can confirm, this change fixes the issue with CurseForge/Twitch apps.  Thank you!
