### ISSUE TITLE
Request: Option to turn off ids on items

### ISSUE THREAD

**Issue by nancikennedy** [silverwind/idTip#65]
I only use this for the spellid function, wherever that is shown in-game. I also use iTip because I like the way the author presents the info in the tooltip, which includes the itemid. It would be convenient if I could disable showing ids on items in your addon, so I'm not duplicating info.

**Comment by silverwind** [comment]
Need an options interface for that which I don't really have the time to implement but contributions are welcome.

**Comment by nancikennedy** [comment]
Thanks for the quick response. LUA has bedeviled me as a language, so my knowledge level is officially "just enough to be dangerous". If I had the time, I would probably jump into it more....cheers and thanks for your efforts :)

**Comment by silverwind** [comment]
Fixed with https://github.com/silverwind/idTip/commit/fb77b8334b5928d315d3bd306d60e3916f70a0f3
