### ISSUE TITLE
Add a license to this repo

### ISSUE THREAD

**Issue by t-mart** [silverwind/idTip#69]
Hey @silverwind,

Would you please consider adding a license to this repository and/or code reuse guidelines?

I'd like to use a snippet of your code at https://github.com/silverwind/idTip/blob/master/idTip.lua#L241, which is a workaround for broken the broken links that Blizzard returns from `GameTooltip:GetItem()` calls for crafting reagents. My project is [here](https://github.com/t-mart/ItemVersion), and the issue is [here](https://github.com/t-mart/ItemVersion/issues/4). You can see in my [code snippet](https://github.com/t-mart/ItemVersion/issues/4#issuecomment-774789806) that, while I am giving you credit in a comment, if you are reserving your copyright, I cannot copy your code.

According to https://choosealicense.com/no-permission/, source code without a license is copyrighted by default.

If you'd like to add a license, people usually just add a file named `LICENSE` to the repository root with the contents of the license you'd like to use. Happy to submit a PR if you're interested.

**Comment by Kherae** [comment]
After looking at it, you basically can't write the code any other way, outside changing a few variable names. there's basically nothing to copyright because of it. Virtually all WoW API/lua  functions.

**Comment by silverwind** [comment]
Thanks for adding it, I forgot it on this repo.
