### ISSUE TITLE
Not working in Burning Crusade Classic 

### ISSUE THREAD

**Issue by Daeveren** [silverwind/idTip#71]
Getting this error at login

Message: Interface\AddOns\idTip\idTip.lua:141: hooksecurefunc(): SetRecipeResultItem is not a function
Time: Wed May 19 19:38:11 2021
Count: 1
Stack: Interface\AddOns\idTip\idTip.lua:141: hooksecurefunc(): SetRecipeResultItem is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@Interface\AddOns\idTip\idTip.lua"]:141: in main chunk

Locals:

**Comment by Kiburan** [comment]
Fix for The Burning Crusade Classic (TBC) at line 29 of idTip.lua: 

Change the last value from 20000 to 30000.
From:
local isClassicWow = select(4,GetBuildInfo()) < 20000

To:
local isClassicWow = select(4,GetBuildInfo()) < 30000

**Comment by Daeveren** [comment]
I can confirm it works and I don't see any errors. Thank you!
