### ISSUE TITLE
SpellID's for enemy player buffs?

### ISSUE THREAD

**Issue by LordNoxington** [silverwind/idTip#75]
Doesn't seem to be showing IDs for buffs/debuffs on enemy players. Would be really useful!

Cheers

**Comment by ItsJustMeChris** [comment]
This would be addressed in 

https://github.com/silverwind/idTip/pull/80
I'll take a look at the current retail interface files later and confirm functionality on my branch is sufficient for current shadowlands and wotlk clients, as well as maintained for dragonflight.

**Comment by silverwind** [comment]
I haven't checked specifically, but as long as it's a standard blizzard buff tooltip, it should work in current version.
