### ISSUE TITLE
Host addon outside of CurseForge

### ISSUE THREAD

**Issue by timmywil** [silverwind/idTip#77]
CurseForge is locking their API out to everyone except Overwolf's own addon manager (see https://www.wowhead.com/news/ads-revenue-and-api-wowup-and-overwolf-split-over-addon-development-325912). Please make this addon available on other platforms besides CurseForge. Options include:

- wago.io: has monetization built in, if that is a concern
- GitHub: package the release into a .zip file that can be downloaded directly from GitHub
- WowUpHub: this works automatically if the release is packaged on GitHub
- WowInterface
- TukUi

The [BigWigs packager](https://github.com/BigWigsMods/packager) can help you set up a GitHub action to do this automatically.

I am personally using WowUp to update addons, and while I very much respect that some addon creators want their work monetized, and believe that they should have the option, I do not support the Overwolf lock-out simply because they want everyone to use their app. If monetization is a priority, I suggest using wago.io as addon hosting, as it allows for monetization of addons, also while using WowUp; which shows they're willing to find solutions, rather than the Overwolf approach of refusing to cooperate.

I don't mind anyone hosting their addons on CurseForge, but please host it outside of CurseForge as well, for those of us who would like to cut ties with CurseForge, but still use your amazing addon ❤️.

If you are no longer maintaining this addon, or just don't have time right now, please let me know if it's okay with you for me to set up hosting on other platforms using a fork. Thanks.

**Comment by silverwind** [comment]
You can install directly from GitHub using clients like WowUp now.
