### ISSUE TITLE
Dragonflight Beta / PTR 10.0 error

### ISSUE THREAD

**Issue by Voxxel** [silverwind/idTip#81]
The addon fails to display 99% of the spell/npc/item/whatever IDs in DF Beta / 10.0 PTR. The only "platform" where it can display the IDs are the Spellbook and the Mounts page - at least what I found so far.

Caught this LUA error in the current DF Beta version (v10.0.45779):
 
```
1x [ADDON_ACTION_BLOCKED] AddOn 'idTip' tried to call the protected function 'SubmitBug()'.
[string "@Interface/AddOns/!BugGrabber/BugGrabber.lua"]:480: in function <Interface/AddOns/!BugGrabber/BugGrabber.lua:480>
[string "=[C]"]: in function `SubmitBug'
[string "@Interface/AddOns/Blizzard_PTRFeedback/Blizzard_PTRFeedback_Frames.lua"]:769: in function `SubmitIssueReport'
[string "@Interface/AddOns/Blizzard_PTRFeedback/Blizzard_PTRFeedback.lua"]:621: in function `func'
[string "@Interface/AddOns/Blizzard_PTRFeedback/Blizzard_PTRFeedback.lua"]:494: in function `TriggerEvent'
[string "@Interface/AddOns/Blizzard_PTRFeedback/Blizzard_PTRFeedback_Events.lua"]:87: in function `eventFunction'
[string "@Interface/AddOns/Blizzard_PTRFeedback/Blizzard_PTRFeedback_Events.lua"]:264: in function <...Blizzard_PTRFeedback/Blizzard_PTRFeedback_Events.lua:260>
``` 
 
```
5x Interface/AddOns/idTip/idTip.lua:144: hooksecurefunc(): SpellButton_OnEnter is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@Interface/AddOns/idTip/idTip.lua"]:144: in main chunk

Locals:
```

**Comment by yoshimo** [comment]
Tainting the ptr feedback interface happens all the time and can mostly be ignored.

**Comment by Voxxel** [comment]
Oh, I see now what are you talking about, it's in the first error message that isn't related. Sorry but most of these lua bugs doesn't tell too much for me. But does that mean the second bug may be related to the addon's general failure in 10.0?

**Comment by yoshimo** [comment]
The second error is a concern.
Functions change, tooltips change and we need to adjust the addon for that.

**Comment by Voxxel** [comment]
Do you see any chance of a fix in the near future? Or it's rooted deeper than just to apply a hotfix?

**Comment by yoshimo** [comment]
> Do you see any chance of a fix in the near future? Or it's rooted deeper than just to apply a hotfix? Afaik, 10.0 is on the PTR too if no DF beta access.

yes: https://github.com/ItsJustMeChris/idTip/tree/beta or #80

**Comment by Voxxel** [comment]
The Chris' version works very well in the Beta, thank you for pointing me out! :)

**Comment by Voxxel** [comment]
No "Issues" tab on Chris' repo so I post it here: 
The DF Beta received a new update to 10.0.2.45969 and your fixed idTip went broken again for some instances, such as NPC IDs on mouseover, Spellbook spell IDs, Quest log panel IDs, most of item IDs - on Character page/Bags/Adventure guide-boss loot list/Mounts tab/Heirlooms tab, and so on. 
However some of them are still working, like Action bar spells, Talent panel spells and maybe more.

**Comment by ItsJustMeChris** [comment]
#82

**Comment by ItsJustMeChris** [comment]
https://github.com/silverwind/idTip/issues/82#issuecomment-1278586483

**Comment by silverwind** [comment]
Should all be fixed now.
