### ISSUE TITLE
beta buggs

### ISSUE THREAD

**Issue by Fleymour** [silverwind/idTip#83]
1x Interface/AddOns/idTip/idTip.lua:144: hooksecurefunc(): SpellButton_OnEnter is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@Interface/AddOns/idTip/idTip.lua"]:144: in main chunk

Locals:

_______________________
1x Interface/AddOns/idTip/idTip.lua:1 (null)

___________________

1x FrameXML\Bindings.xml:1 Interface/AddOns/idTip/idTip.lua:1 (null)

**Comment by ItsJustMeChris** [comment]
Use https://github.com/ItsJustMeChris/idTip/tree/beta

**Comment by silverwind** [comment]
Fixed in latest releases.
