### ISSUE TITLE
Please update to 10.0

### ISSUE THREAD

**Issue by Mini-Dragon** [silverwind/idTip#86]
Due to API change, some GameTooltip script handlers have been removed in 10.0.

Please update if you are free.

**Comment by yoshimo** [comment]
Use https://github.com/ItsJustMeChris/idTip-Community-Fork

**Comment by Mini-Dragon** [comment]
this fork makes this addon huge... and harder to understand the code

**Comment by silverwind** [comment]
On it, Blizzard has broken half of the tooltip API with this update. At least current master should not error anymore.

**Comment by Mini-Dragon** [comment]
Thanks for the update, I will test and feedback if in need.

**Comment by silverwind** [comment]
It's compatible, but I'm not really done yet as I still need to adapt to the new APIs to show missing IDs again.

**Comment by silverwind** [comment]
Fixed with [10.3.0](https://github.com/silverwind/idTip/commit/b680cd23aaf0d8599a36079b3cf7d885de43a10c)
