### ISSUE TITLE
solve some error problem 解决一个小报错

### ISSUE THREAD

**Issue by chemhunter** [silverwind/idTip#87]
If it shows error with the word "contains"，you can open the file "idTip\lib\shared.lua", replace "**local function contains**" with "**function contains**", then save the file.

如果报错提示中有“contains”，请打开文件 "idTip\lib\shared.lua", 将 "**local function contains**" 替换成 "**function contains**", 保存.

**Comment by silverwind** [comment]
This seems to refer to the fork, not this repo.
