### ISSUE TITLE
As of prepatch to dragonflight it no longer works.

### ISSUE THREAD

**Issue by fisken1991** [silverwind/idTip#88]
Bugsack reports:

 

1x Interface/AddOns/idTip/idTip.lua:1 (null)

**Comment by Kainie85** [comment]
These are the 3 errors I get:

1x FrameXML\Bindings.xml:1 Interface/AddOns/idTip/idTip.lua:1 (null)

1x Interface/AddOns/idTip/idTip.lua:1 (null)

1x Interface/AddOns/idTip/idTip.lua:144: hooksecurefunc(): SpellButton_OnEnter is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@Interface/AddOns/idTip/idTip.lua"]:144: in main chunk

Locals:

**Comment by yoshimo** [comment]
just use https://github.com/ItsJustMeChris/idTip-Community-Fork

**Comment by silverwind** [comment]
Fixed with [10.3.0](https://github.com/silverwind/idTip/commit/b680cd23aaf0d8599a36079b3cf7d885de43a10c)
