### ISSUE TITLE
Error on achievement

### ISSUE THREAD

**Issue by solitha** [silverwind/idTip#89]
Sure glad to see this one working again!

1x idTip/idTip.lua:284: attempt to index global 'AchievementFrameAchievementsContainer' (a nil value)
[string "@idTip/idTip.lua"]:284: in function <idTip/idTip.lua:282>
[string "=[C]"]: in function `LoadAddOn'
[string "@FrameXML/UIParent.lua"]:536: in function `UIParentLoadAddOn'
[string "@FrameXML/UIParent.lua"]:663: in function `AchievementFrame_LoadUI'
[string "@FrameXML/AlertFrames.lua"]:465: in function <FrameXML/AlertFrames.lua:458>

Locals:
_ = Frame {
 0 = <userdata>
}
_ = "ADDON_LOADED"
what = "Blizzard_AchievementUI"
(*temporary) = <function> defined =[C]:-1
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = nil
(*temporary) = "attempt to index global 'AchievementFrameAchievementsContainer' (a nil value)"
hookScript = <function> defined @idTip/idTip.lua:43
addLine = <function> defined @idTip/idTip.lua:49
kinds = <table> {
 enchant = "EnchantID"
 source = "SourceID"
 mount = "MountID"
 companion = "CompanionID"
 unit = "NPC ID"
 currency = "CurrencyID"
 item = "ItemID"
 species = "SpeciesID"
 quest = "QuestID"
 bonus = "BonusID"
 visual = "VisualID"
 spell = "SpellID"
 talent = "TalentID"
 ability = "AbilityID"
 artifactpower = "ArtifactPowerID"
 achievement = "AchievementID"
 gem = "GemID"
 icon = "IconID"
 equipmentset = "EquipmentSetID"
 macro = "MacroID"
 criteria = "CriteriaID"
}
hook = <function> defined @idTip/idTip.lua:37
_G = <table> {
 UpdateOnBarHighlightMarksBySpell = <function> defined @FrameXML/ActionButton.lua:82
 ERR_OUT_OF_CHI = "Not enough chi"
 DH_HAVOC_CORE_ABILITY_2 = "Strong melee attack that consumes Fury. If it critical strikes, some Fury is refunded."
 MultiCastActionButton6Cooldown = MultiCastActionButton6Cooldown {
 }
 SettingsSliderOptionsMixin = <table> {
 }
 GetTrainerServiceTypeFilter = <function> defined =[C]:-1
 UNIT_NAMES_COMBATLOG_TOOLTIP = "Color unit names."
 AchievementFrameStatsBG = AchievementFrameStatsBG {
 }
 HUD_EDIT_MODE_SETTING_ACTION_BAR_HIDE_BAR_ART = "Hide Bar Art"
 LE_GAME_ERR_CHAT_RAID_RESTRICTED_TRIAL = 774
 SPELL_FAILED_CUSTOM_ERROR_71 = "This partygoer wants to dance with you."
 LE_GAME_ERR_PET_SPELL_TARGETS_DEAD = 417
 ERROR_CLUB_TICKET_COUNT_AT_MAX_COMMUNITY = "Can't create any more invite links for this community."
 RecruitAFriendFrame = RecruitAFriendFrame {
 }
 TutorialFrameLeft19 = TutorialFrameLeft19 {
 }
 MultiCastActionButton2Cooldown = MultiCastActionButton2Cooldown {
 }
 ERR_TRADE_EQUIPPED_BAG = "You can't trade equipped bags."
 PVP_RANK_6_1 = "Corporal"
 MultiBarLeftButton7 = MultiBarLeftButton7 {
 }
 OPTION_TOOLTIP_SHOW_MULTIBAR4 = "Attached to the left side of Right Action Bar 1 by default"
 LE_GAME_ERR_INVALID_FOLLOW_PVP_COMBAT = 371
 MerchantItem1AltCurrencyFrameItem1Text = MerchantItem1AltCurrencyFrameItem1Text {
 }
 PROFESSIONS_COLUMN_REAGENTS_NONE = "None"
 OPTION_TOOLTIP_ACTION_BUTTON_USE_KEY_DOWN = "Action button keybinds will respond on key down, rather than on key up."
 BINDING_NAME_NAMEPLATES = "Show Enemy Name Plates"
 INSTANCE_UNAVAILABLE_OTHER_TEMPORARILY_DISABLED = "%s cannot enter. This instance is temporarily disabled."
 EncounterDetails_SpellAurasScrollScrollChildFrame = EncounterDetails_SpellAurasScrollScrollChildFrame {
 }
 MultiBarBottomRightButton8Shine5 = MultiBarBottomRightButton8Shine5 {
 }
 COVENANT_MISSIONS_HEALTH = "Health"
 MAIL_LETTER_TOOLTIP = "Click to make a permanent
copy of this letter."
 UnitFrameManaBar_UnregisterDefaultEvents = <function> defined @FrameXML/UnitFrame.lua:898
 PVPReadyDialogBottomArt = PVPReadyDialogBottomArt {
 }
 MultiBar6Button4Flash = MultiBar6Button4Flash {
 }
 CALENDAR_RAID_RESET_DESCRIPTION = "%1$s resets at %2$s."
 CHAT_CONFIG_OTHER_COMBAT = <table> {
 }
 WorldQuestTrackerWorldMapPOIWorldQuestTrackerWorldSummarySquarePOI2BorderShineAnimation3 = WorldQuestTrackerWorldMapPOIWorldQuestTrackerWorldSummarySquarePOI2BorderShineAnimation3 {
 }
 FCFDockOverflowButton_OnClick = <function> defined @FrameXML/FloatingChatFrame.lua:2398
 TutorialFrameRight19 = TutorialFrameRight19 {
 }
 MoneyFrame_OnEvent = <function> defined @FrameXML/MoneyFrame.lua:202
 BN_UNABLE_TO_RESOLVE_NAME = "Unable to whisper '%s'. Blizzard services may be unavailable."
 AutoCompleteEditBox_OnKeyDown = <function> defined @FrameXML/AutoComplete.lua:368
 WorldQuestTrackerWorldMapPOIWorldQuestTrackerWorldSummarySquarePOI7BorderShineAnimation1 = WorldQuestTr

**Comment by silverwind** [comment]
Fixed with 10.2.2.
