### ISSUE TITLE
Nil value bug

### ISSUE THREAD

**Issue by solitha** [silverwind/idTip#91]
After updating to 10.3.1. Looks a lot like the last one I reported but the line numbers are a little different.

19x idTip/idTip.lua:57: attempt to concatenate local 'name' (a nil value)
[string "@idTip/idTip.lua"]:57: in function <idTip/idTip.lua:49>
[string "@idTip/idTip.lua"]:115: in function <idTip/idTip.lua:111>
[string "@idTip/idTip.lua"]:133: in function <idTip/idTip.lua:126>
[string "=(tail call)"]: ?
[string "=[C]"]: in function `securecallfunction'
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:60: in function <SharedXML/Tooltip/TooltipDataHandler.lua:55>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:77: in function <SharedXML/Tooltip/TooltipDataHandler.lua:76>
[string "@SharedXML/Tooltip/TooltipDataHandler.lua"]:116: in function <SharedXML/Tooltip/TooltipDataHandler.lua:106>
[string "=[C]"]: in function `resume'
[string "@TellMeWhen/TellMeWhen.lua"]:2802: in function <TellMeWhen/TellMeWhen.lua:2763>

Locals:
tooltip = GameTooltip {
 0 = <userdata>
 SetQuestLogRewardSpell = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestPartyProgress = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 ProcessLineData = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:303
 SetPvpTalent = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetRuneforgeResultItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetHyperlink = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnit = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetAzeriteEssence = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetVoidDepositItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetVoidWithdrawalItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetInfoBackdropStyle = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:338
 SetSocketGem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetLootCurrency = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetSlottedKeystone = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetWorldCursor = <function> defined @FrameXML/GameTooltip.lua:952
 SetLootItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 GetUnit = <function> defined @FrameXML/GameTooltip.lua:994
 SetOwnedItemByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestLogSpecialItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetRecipeReagentItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestCurrency = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetWeeklyReward = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetMerchantItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetPvpBrawl = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetSpellByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetSocketedRelic = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 ProcessInfo = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:236
 ProcessLines = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:293
 SetInventoryItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetLootRollItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetUnitDebuffByAuraInstanceID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetBagItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 info = <table> {
 }
 SetAction = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 OnLoad = <function> defined @FrameXML/GameTooltip.lua:927
 SetTransmogrifyItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetInventoryItemByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetQuestLogCurrency = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetCurrencyByID = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetVoidItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 GetSpell = <function> defined @FrameXML/GameTooltip.lua:990
 SetItemKey = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetSpellBookItem = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetCompanionPet = <function> defined @SharedXML/Tooltip/TooltipDataHandler.lua:444
 SetTraitEntry = <function> defined @Shared

**Comment by silverwind** [comment]
Try 10.3.2.

**Comment by solitha** [comment]
Fixed! Thank you!
