### ISSUE TITLE
10.5.0 Lua error 

### ISSUE THREAD

**Issue by b-morgan** [silverwind/idTip#97]
1x Interface\FrameXML\Bindings.xml:1 idTip/idTip.lua:1 idTip/idTip.lua:454: 'end' expected (to close 'function' at line 112) near '<eof>'

**Comment by silverwind** [comment]
Try 10.5.1, can not test right now.

**Comment by b-morgan** [comment]
Line 116: "else if" should be "elseif"

**Comment by silverwind** [comment]
Did that in https://github.com/silverwind/idTip/commit/8c6138621d6b67c440abad04070b7dcc70b7b326.

**Comment by b-morgan** [comment]
Great minds think alike 😁
